### ISSUE TITLE
As a developer I want to prepeare Sourcetree, GIT and InteliJ for the project start.

### ISSUE THREAD

**Issue by wi20b080** [wi20b080/MaintenanceMonitor#2]

**Comment by wi20b080** [comment]
Projekt mit Sourcetree geklont und mit InteliJ mit GITHub verbunden

**Comment by Igesa** [comment]
Ich bin auch gerade fertig

**Comment by wi20b063** [comment]
Nach einigen Problemen mit der JDK 15, hab ich es nun auch geschafft und alles erstellt.
